name: test vcs install

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/test-vcs-install.yml"
      - ".gitattributes"
      - "composer.json"
      - "src/**.php"
      - "README.md"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/test-vcs-install.yml"
      - ".gitattributes"
      - "composer.json"
      - "src/**.php"
      - "README.md"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - "8.1"
          - "8.2"
          - "8.3"

    steps:
      - name: Checkout (just for context)
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Create project directory
        run: mkdir test-project

      - name: Create minimal composer.json
        working-directory: test-project
        run: |
          echo '{
            "name": "dummy/test-project",
            "description": "Temporary test project",
            "repositories": [
              {
                "type": "vcs",
                "url": "https://github.com/asokol1981/abstract-mold"
              }
            ],
            "require": {
              "asokol1981/abstract-mold": "dev-main"
            },
            "minimum-stability": "dev",
            "prefer-stable": true
          }' > composer.json

      - name: Composer update
        working-directory: test-project
        run: composer update

      - name: Create test.php to validate package functionality
        working-directory: test-project
        run: |
          echo "<?php
          require __DIR__ . '/vendor/autoload.php';

          use ASokol1981\\AbstractMold\\AbstractImmutableMold;

          new class([], []) extends AbstractImmutableMold {
              protected function publicFields(): array {
                  return ['foo', 'bar'];
              }
              protected function validatedData(): array {
                  return [];
              }
          };

          echo 'Smoke test passed.' . PHP_EOL;
          " > test.php

      - name: Run smoke test
        working-directory: test-project
        run: php test.php
